resources:
  - name: hld3-git-repo
    type: git
    source:
      uri: https://github.com/hld3/testing.git
      branch: master

  - name: python-image
    type: docker-image
    source: {repository: python}

  - name: timer
    type: time
    source:
      interval: 30m

jobs:
#  - name: simple-test
#    public: true
#    plan:
#      - get: random-testing
#      - task: print-something
#        file: random-testing/echo_hello.yml

  - name: run-python-file
    public: true
    plan:
    - get: hld3-git-repo
      trigger: true
    - get: python-image
    - get: timer
      trigger: true
    - task: python-print
      image: python-image
      config:
        platform: linux
        inputs:
          - name: hld3-git-repo
        run: 
          path: python
          args: ["hld3-git-repo/print_hello.py"]
#          args: ["--version"]
